package com.genyuya.entity;

// Generated 2016-5-2 20:26:38 by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "genyuya")
public class Activity implements java.io.Serializable {

	private Integer id;
	private String actName;
	private String time;
	private String place;
	private String abstractContent;
	private String qrcode;
	private Integer applyNum;

	private Integer maxNum;
	private Integer kidNum;
	private Set<Usrinfo> usrinfos = new HashSet<Usrinfo>(0);
	private Set<Usrinfo> usrinfos_1 = new HashSet<Usrinfo>(0);

	public Activity() {
	}

	public Activity(String actName, String time, String place,
			String abstractContent, String qrcode, Integer applyNum,Integer maxNum,Integer kidNum,
			Set<Usrinfo> usrinfos, Set<Usrinfo> usrinfos_1) {
		this.actName = actName;
		this.time = time;
		this.place = place;
		this.abstractContent = abstractContent;
		this.qrcode = qrcode;
		this.applyNum = applyNum;
		this.usrinfos = usrinfos;
		this.usrinfos_1 = usrinfos_1;
		this.maxNum=maxNum;
		this.kidNum=kidNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "actName")
	public String getActName() {
		return this.actName;
	}

	public void setActName(String actName) {
		this.actName = actName;
	}

	@Column(name = "time", length = 50)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "place")
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "abstract_content", length = 65535)
	public String getAbstractContent() {
		return this.abstractContent;
	}

	public void setAbstractContent(String abstractContent) {
		this.abstractContent = abstractContent;
	}

	@Column(name = "QRcode")
	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	@Column(name = "applyNum")
	public Integer getApplyNum() {
		return this.applyNum;
	}

	public void setApplyNum(Integer applyNum) {
		this.applyNum = applyNum;
	}

	@Column(name="maxNum")
	public Integer getMaxNum() {
		return maxNum;
	}

	public void setMaxNum(Integer maxNum) {
		this.maxNum = maxNum;
	}
	@Column(name="kidNum")
	public Integer getKidNum() {
		return kidNum;
	}

	public void setKidNum(Integer kidNum) {
		this.kidNum = kidNum;
	}

	@ManyToMany(cascade= CascadeType.ALL)
	@JsonIgnoreProperties(value = {"activities","activities_1"})
	@JoinTable(name = "join_relation", catalog = "genyuya", joinColumns = { @JoinColumn(name = "activity_id", nullable = false, updatable = true) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = true) })
	public Set<Usrinfo> getUsrinfos() {
		return this.usrinfos;
	}

	public void setUsrinfos(Set<Usrinfo> usrinfos) {
		this.usrinfos = usrinfos;
	}

	@ManyToMany(mappedBy="activities",cascade= CascadeType.ALL)
	@JsonIgnoreProperties(value = {"activities_1","activities"})
	//@JoinTable(name = "apply_relation", catalog = "genyuya", joinColumns = { @JoinColumn(name = "activity_id", nullable = false, updatable = true) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = true) })
	public Set<Usrinfo> getUsrinfos_1() {
		return this.usrinfos_1;
	}

	public void setUsrinfos_1(Set<Usrinfo> usrinfos_1) {
		this.usrinfos_1 = usrinfos_1;
	}

}
