package com.genyuya.entity;

// Generated 2016-5-2 20:26:38 by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Usrinfo generated by hbm2java
 */
@Entity
@Table(name = "usrinfo", catalog = "genyuya")
public class Usrinfo implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String name;
	private String phone;
	private String sex;
	private Integer medal;

	private Set<Activity> activities = new HashSet<Activity>(0);
	private Set<Activity> activities_1 = new HashSet<Activity>(0);

	public Usrinfo() {
	}

	public Usrinfo(String openid) {
		this.openid = openid;
	}

	public Usrinfo(String openid, String name, String phone, String sex,
			Integer medal, Set<Activity> activities, Set<Activity> activities_1) {
		this.openid = openid;
		this.name = name;
		this.phone = phone;
		this.sex = sex;
		this.medal = medal;
		this.activities = activities;
		this.activities_1 = activities_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "openid", nullable = false, length = 32)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", length = 16)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "sex", length = 8)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "medal")
	public Integer getMedal() {
		return this.medal;
	}

	public void setMedal(Integer medal) {
		this.medal = medal;
	}

	@ManyToMany(cascade = CascadeType.ALL)
	@JsonIgnoreProperties(value = {"usrinfos_1","usrinfos"})
	@JoinTable(name = "apply_relation", catalog = "genyuya", joinColumns = { @JoinColumn(name = "user_id") }, inverseJoinColumns = { @JoinColumn(name = "activity_id") })
	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JsonIgnoreProperties(value = {"usrinfos","usrinfos_1"})
	@JoinTable(name = "join_relation", catalog = "genyuya", joinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = true) }, inverseJoinColumns = { @JoinColumn(name = "activity_id", nullable = false, updatable = false) })
	public Set<Activity> getActivities_1() {
		return this.activities_1;
	}

	public void setActivities_1(Set<Activity> activities_1) {
		this.activities_1 = activities_1;
	}

}
